### ISSUE TITLE
libTensorStream.so: undefine xxxxx

### ISSUE THREAD

**Issue by li829** [Fonbet/argus-tensor-stream#10]
When I try to use c_sample, it comes out the error:
/home/liyuewen/app/tensor-stream/build/libTensorStream.so: undefined reference to `av_hwdevice_ctx_init'
/home/liyuewen/app/tensor-stream/build/libTensorStream.so: undefined reference to `av_hwframe_transfer_data'
/home/liyuewen/app/tensor-stream/build/libTensorStream.so: undefined reference to `avcodec_send_packet'
/home/liyuewen/app/tensor-stream/build/libTensorStream.so: undefined reference to `av_hwdevice_ctx_alloc'
/home/liyuewen/app/tensor-stream/build/libTensorStream.so: undefined reference to `avcodec_receive_frame'
/home/liyuewen/app/tensor-stream/build/libTensorStream.so: undefined reference to `avcodec_parameters_to_context'
/home/liyuewen/app/tensor-stream/build/libTensorStream.so: undefined reference to `av_hwdevice_find_type_by_name'

**Comment by BykadorovR** [comment]
Hi @li829 
Looks like you faced the issue with FFmpeg installation, so you'd better reinstall it. As reference you can take command lines from [Dockerfile](https://github.com/osai-ai/tensor-stream/blob/0827723d5ad3f970325d8446cf451894891cac08/Dockerfile) (starting from 15 line till 35)

**Comment by li829** [comment]
Thank you! My problem has been solved. It is because I install FFmpeg in my own path, but Cmaklists choose system's FFmpeg. So I change the it to my FFmpeg path, then it works.
