### ISSUE TITLE
gpu memory

### ISSUE THREAD

**Issue by Shengxiaolin** [Fonbet/argus-tensor-stream#12]
hi,i find the gpu memory increase slowly when TensorStream restart(viedo is ending) in a while loop,maybe some ptr do not release when TensorStream throw runtime error?

**Comment by BykadorovR** [comment]
Hi @Shengxiaolin,
Could you please provide more details? C++/Python, Windows/Linux, execution line/sample code? It will help a lot, thanks!

**Comment by Shengxiaolin** [comment]
ok ~ ,i use this repo on linux in my c++ project,and code is looks like this: 
`int main(){
	
	while(true){

		TensorStream reader;

	    reader.enableLogs(0);
		reader.enableNVTX();

	    int sts = reader.initPipeline("test.mp4", 5, 0, 5); // maxConsumers = 5, cudaDevice = 0, decoderBuffer = 10
		if (sts != VREADER_OK) {
	        reader.endProcessing();
	        return 0;
	    }

	    reader.skipAnalyzeStage();
		CHECK_STATUS(sts);

	    std::thread pipeline([&] { reader.startProcessing(); });

	    ColorOptions colorOptions = { FourCC::BGR24 };
		colorOptions.planesPos = Planes::PLANAR;
		colorOptions.normalization = false;
		FrameParameters frameParameters = {m_resizeOptions, colorOptions, m_cropOptions};

	   	while(true){
	   		
	        try{
	            auto result = reader.getFrame<unsigned char>("first", 0, frameParameters);
	            auto tensor = std::get<0>(result);
	            auto rawData = std::shared_ptr<unsigned char>(new unsigned char[(int)(3 * cap_width * cap_height)], std::default_delete<unsigned char[]>());
	            cudaError err = cudaMemcpy(rawData.get(), tensor, 3 * cap_width * cap_height * sizeof(unsigned char), cudaMemcpyDeviceToHost);
	            if(err!=0) break;
	            cv::Mat frame = raw2bgr(rawData.get(), cap_width, cap_height);  // self-def
	            cudaFree(tensor);
	        }catch (std::runtime_error e){
	            break;
	    	}
	   	}

		reader.endProcessing();
	   	pipeline.join();
	}


}`

**Comment by Shengxiaolin** [comment]
ok ~ ,i use this repo on linux in my c++ project and code is looks like this:

    while(true){

		TensorStream reader;

	        reader.enableLogs(0);
		reader.enableNVTX();

	        int sts = reader.initPipeline("test.mp4", 5, 0, 5); // maxConsumers = 5, cudaDevice = 0, decoderBuffer = 10
		if (sts != VREADER_OK) {
	            reader.endProcessing();
	            return 0;
	        }

	        reader.skipAnalyzeStage();
		CHECK_STATUS(sts);

	        std::thread pipeline([&] { reader.startProcessing(); });

	        ColorOptions colorOptions = { FourCC::BGR24 };
		colorOptions.planesPos = Planes::PLANAR;
		colorOptions.normalization = false;
		FrameParameters frameParameters = {m_resizeOptions, colorOptions, m_cropOptions};

	   	while(true){
	   		
	            try{
	                auto result = reader.getFrame<unsigned char>("first", 0, frameParameters);
	                auto tensor = std::get<0>(result);
	                auto rawData = std::shared_ptr<unsigned char>(new unsigned char[(int)(3 * cap_width * cap_height)], std::default_delete<unsigned char[]>());
	                cudaError err = cudaMemcpy(rawData.get(), tensor, 3 * cap_width * cap_height * sizeof(unsigned char), cudaMemcpyDeviceToHost);
	                if(err!=0) break;
	                cv::Mat frame = raw2bgr(rawData.get(), cap_width, cap_height);  // self-def
	                cudaFree(tensor);
	            }catch (std::runtime_error e){
	                break;
	    	    }
	   	}

		reader.endProcessing();
	   	pipeline.join();
	}

**Comment by BykadorovR** [comment]
Thanks for reproducer! I will check it locally and return back with solution.

**Comment by BykadorovR** [comment]
Hi @Shengxiaolin,
I [fixed](https://github.com/osai-ai/tensor-stream/commit/8d603949aea810e8d1049cfb0479c5498ffad912) the issue, please try to execute your scenario and check if issue has gone.
Thanks!

**Comment by Shengxiaolin** [comment]
solved, thanks!
