### ISSUE TITLE
Program crashed when startProcessing

### ISSUE THREAD

**Issue by firebobo** [Fonbet/argus-tensor-stream#14]
![image](https://user-images.githubusercontent.com/6874380/93039355-dd26ba80-f679-11ea-9606-5087de1f2140.png)
As you can see in the picture that ‘gdb core file’，I suspect the byteData is null，How did this happen

**Comment by BykadorovR** [comment]
Hi @firebobo,
Looks like bitstream contains syntaxis TensorStream can't parse. You can disable analyze stage and see if FFmpeg can process it.
Also it would be very nice if you share this bitstream so I can test it locally.

**Comment by firebobo** [comment]
tks,BykadorovR, i try to skip the analyze stage, the program is pass
I am sorry that my camera can not access,because it  is in the local area network,but i see so manay 'miss the packet' in the console when i ffplay the stream
