### ISSUE TITLE
Multiple camera stream

### ISSUE THREAD

**Issue by thunanguyen** [Fonbet/argus-tensor-stream#22]
Hi, thank you for this great work. I've used it and work very fast with a single camera. However, I want to scale my program to multiple cameras. So I want to ask if there is any way to use this library for multiple cameras and feed the image to a pytorch models. I saw the example for multiple cameras in the README but it is unclear to me how to pass the result tensor to a pytorch model and do a batch inference with that model.

**Comment by BykadorovR** [comment]
Hi @thunanguyen,
You can check [different_streams.py](https://github.com/osai-ai/tensor-stream/blob/master/python_examples/different_streams.py) sample, it shows how to run several instances of tensor-stream. You can specify for every instance different streams/any other settings.

**Comment by thunanguyen** [comment]
Thanks. I think I will close the issue for now.
