### ISSUE TITLE
latency problems

### ISSUE THREAD

**Issue by JonathanLehner** [Fonbet/argus-tensor-stream#5]
HI! for me the stream is processed with 24fps on the pc with gpu. However somewhere there is additional latency. when i stream my webcam from my laptop to the pc the latency is very low <100ms. however, when i run neural_style.py the latency of the processed stream is > 7 seconds. I tried to change some ffmpeg settings but it was unsuccessful

**Comment by BykadorovR** [comment]
Hi @JonathanLehner,
So if I understand you correctly you're trying to use neural_style.py sample with your own stream (different from used in neural_style.py sample) and observe processing time > 7 seconds for 1 frame?
Could you please try to execute neural_style.py with default settings and check if latencies are correct? Please also enable logs in neural_style.py sample for your stream by passing additional parameters to command line and attach result log file here:
python neural_style.py **-v HIGH -vd FILE**

**Comment by JonathanLehner** [comment]
I also executed it with the sample video "vod/big_buck_bunny.mp4", but it is hard to know there how much the latency is since I don't know when exactly the stream arrives at my PC. So I made my own rtmp stream and 1) opened it directly with mplayer on the pc, and then i also 2) opened the stream with argus-tensor-stream (inside docker) for processing, and then opened the generated udp stream with mplayer. in the first case my latency is very low, but if it goes through argus-tensor then the latency is high.

**Comment by JonathanLehner** [comment]
should the flags be "-v HIGH -vd FILE" exactly? or replace FILE?

**Comment by BykadorovR** [comment]
It should be exactly the same as I linked (you can check [README](https://github.com/Fonbet/argus-tensor-stream/blob/master/README.md#samples) for more information).
Could you also provide command lines so I can try them locally?

**Comment by BykadorovR** [comment]
@JonathanLehner Just realised that log file generation isn't available in neural_style.py example via command line, so you need to add:
`reader.enable_logs(LogsLevel.HIGH, LogsType.FILE)`
to neural_style.py after reader instance creation (`reader = TensorStreamConverter(...) `)
and `from tensor_stream import LogsLevel, LogsType` to import section.

**Comment by BykadorovR** [comment]
> I also executed it with the sample video "vod/big_buck_bunny.mp4", but it is hard to know there how much the latency is since I don't know when exactly the stream arrives at my PC. So I made my own rtmp stream and 1) opened it directly with mplayer on the pc, and then i also 2) opened the stream with argus-tensor-stream (inside docker) for processing, and then opened the generated udp stream with mplayer. in the first case my latency is very low, but if it goes through argus-tensor then the latency is high.

If you try to open your RTMP stream via argus-tensor using neural_style.py example then after frame decoding + post-processing, style model is applied to every frame, so if compare two approaches: just reading RTMP and using neural_style.py the last one will have bigger lattency due to style model. Performance of overall pipeline: decoding + VPP + model depends on your hardware configuration.

**Comment by BykadorovR** [comment]
@JonathanLehner is the issue still relevant?

**Comment by JonathanLehner** [comment]
yes, sorry for the delay. I have been very busy during the week, I will have a look again tomorrow
