### ISSUE TITLE
C++ version of the real debugging does not pass.

### ISSUE THREAD

**Issue by TimVerion** [Fonbet/argus-tensor-stream#6]
Can you write ffmpeg and the required environment in detail? C++ version of the real debugging does not pass.

**Comment by BykadorovR** [comment]
Hello @TimVerion,
Could you please specify the OS?

**Comment by TimVerion** [comment]
I'm using ubuntu16.4 to compile and it will work but the code in c_example runs the initialization error and I add the code avcodec_register_all(); Then I found that the program had been stuck in "Decoder" : "avcodec_parameters_to_context(decoderContext, state.parser->getStreamHandle()->codecpar); "Check that" state.parser->getStreamHandle()->codecpar "is empty

**Comment by BykadorovR** [comment]
So you executed c_example without any changes and it returned the error? Can you please add the initial error returned from TensorStream?
Also you can find all library dependencies and their versions in Dockerfile:
https://github.com/Fonbet/argus-tensor-stream/blob/master/Dockerfile

**Comment by TimVerion** [comment]
TID: 140632670492672 Initializing()  +
TID: 140632670492672 Chosen GPU: 0
TID: 140632670492672 Error status != 0, status: -1330794744
TID: 140632670492672 /home/myh/CLionProjects/argus-tensor-stream/src/Parser.cpp Init 314
TID: 140632670492672 Error status != 0, status: -1330794744
TID: 140632670492672 /home/myh/CLionProjects/argus-tensor-stream/src/Wrappers/WrapperC.cpp initPipeline 46
TID: 140632670492672 End processing async part
TID: 140632670492672 End processing sync part start
TID: 140632670492672 End processing sync part end
TID: 140632670492672 Initializing()  +
TID: 140632670492672 Chosen GPU: 0
TID: 140632670492672 Error status != 0, status: -1330794744
TID: 140632670492672 /home/myh/CLionProjects/argus-tensor-stream/src/Parser.cpp Init 314
TID: 140632670492672 Error status != 0, status: -1330794744
TID: 140632670492672 /home/myh/CLionProjects/argus-tensor-stream/src/Wrappers/WrapperC.cpp initPipeline 46

**Comment by BykadorovR** [comment]
Have you tested c_example on your own stream file or used default one? TensorStream returned error from avformat_open_input() call on stream parser stage so looks like either you used some unsupported file or had issues with default file access via rtmp.

**Comment by TimVerion** [comment]
First of all, thank you for your answer，These streams, including those in the instance, I can open using VLC, and I can run the results using the python version. For example“rtmp://127.0.0.1/live/livestreamse-pc”.Can you provide a supported format, for now I use the SRS local startup stream (h.264)

**Comment by BykadorovR** [comment]
TensorStream supports h.264 codec in any container supported by ffmpeg demuxer. It's strange that the same file works with Python but not with C++. Can you please share any file that don't work in c_example so I can test it on my environment?

**Comment by TimVerion** [comment]
rtmp://streaming.sportlevel.com/relay/Efie7shoo3aeriexnhl
The default value given in this file is the same error. Here I downloaded an episode of spongebob on the Internet, and the format is h264, and whether I need to add "av_register_all();"
![2020-02-11 00-17-39屏幕截图](https://user-images.githubusercontent.com/43239900/74168015-128ea400-4c64-11ea-9c4a-f375abf9ff73.png)

**Comment by BykadorovR** [comment]
Can you please try to reinstall your ffmpeg to one from Dockerfile:
https://github.com/Fonbet/argus-tensor-stream/blob/master/Dockerfile
Looks like you have version FFmpeg < 4.0 (https://github.com/leandromoreira/ffmpeg-libav-tutorial/issues/29) so you face the issue when av_register_all() is required.

**Comment by BykadorovR** [comment]
I just double checked c_example in master branch and it worked fine, so looks like you have some environment issue. You can either try to create Docker container using Dockerfile https://github.com/Fonbet/argus-tensor-stream/blob/master/Dockerfile or install all dependencies from it manually.

**Comment by TimVerion** [comment]
Now my nv-codec-headers and ffmpeg are configured according to the Dockfile. If I do not add "av_register_all ()" or the same error, a reference exception will appear in the Decoder's avcodec_parameters_to_context

**Comment by TimVerion** [comment]
After adding "av_register_all ()", "av_dump_format" cannot be used to print the information. I use the compiled ffmepg to decode directly and print the information. The result is as follows:
Input #-1, flv, from 'rtmp://127.0.0.1:1935/live/livestreamse-pc':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    encoder         : Lavf58.29.100
    server          : SRS/2.0.263(ZhouGuowen)
    srs_primary     : SRS/2.0release
    srs_authors     : winlin,wenjie.zhao
    server_version  : 2.0.263
  Duration: N/A, start: 0.000000, bitrate: 582 kb/s
    Stream #-1:0: Data: none
    Stream #-1:1: Audio: aac (HE-AAC), 44100 Hz, stereo, fltp, 31 kb/s
    Stream #-1:2: Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 624x480, 550 kb/s, 25 fps, 25 tbr, 1k tbn, 50 tbc

**Comment by BykadorovR** [comment]
Can you please add your PC configuration (CPU and GPU at least), also can you try to execute C++ tests from argus-tensor-stream/tests folder (first you need to build them as c_example), maybe it will allow us to localize the issue. BTW, I still think you have some old version of ffmpeg on your PC which is used by default instead of new one (I can't reproduce your behavior locally, also I don't set av_register_all() and all codecs/muxers/demuxers are found and registered automatically).
Can you also test rtmp://37.228.119.44:1935/vod/big_buck_bunny.mp4 stream?

**Comment by TimVerion** [comment]
207/5000 
Thank you very much for your answer. The problem has been solved. As expected, I told you about the environment.

I will"

Target_link_libraries (${PROJECT_NAME} ${FFMPEG_AVCODEC} ${FFMPEG_AVUTIL} ${FFMPEG_AVFORMAT})"

Change to

"Target_link_libraries (${PROJECT_NAME} avcodec avformat avutil)"

Then it can work normally.
