### ISSUE TITLE
Whether to support the video stream of h265?

### ISSUE THREAD

**Issue by TimVerion** [Fonbet/argus-tensor-stream#7]
Whether to support the video stream of h265?
The program compiles well and h264 video and RTSP streams work fine, but how do you support h265 video streams

**Comment by BykadorovR** [comment]
We haven't tested tensor-stream with h.265 bitstreams. Moreover some functions/features like [Parser::Analyze](https://github.com/osai-ai/tensor-stream/blob/0072af2f182d58dc4e34be708cd59397aef64af2/src/Parser.cpp#L146) which parse raw bitstream definitely won't work due to h.264 syntax dependencies.
We have plans to add h.265 support but not in near release.

**Comment by TimVerion** [comment]
Thank you very much for your reply. I am also changing the parsing code in parser.h, but I have no idea. I am looking forward to your update

**Comment by TimVerion** [comment]
Also, the code actually parsed the video stream and the **avformat_find_stream_info** interface started reporting errors. Is this the ffmpeg version? Thank you very much for your reply

**Comment by BykadorovR** [comment]
This function isn't mandatory, you can always [disable](https://github.com/osai-ai/tensor-stream/blob/0072af2f182d58dc4e34be708cd59397aef64af2/python_examples/simple.py#L98) it. But I can't say whether any other issues with h.265 will appear or not.
If Parser::Analyze is called it will report errors to cout or file depends on log type you set. You can find more details either in [README](https://github.com/osai-ai/tensor-stream#samples) samples section (**-v** and **-vd** arguments) or in [samples](https://github.com/osai-ai/tensor-stream/blob/0072af2f182d58dc4e34be708cd59397aef64af2/python_examples/simple.py#L91).
BTW, I'm not aware of any Parser::Analyze + avformat_find_stream_info issues, if you thinks it's tensor-stream issue please report it.

**Comment by TimVerion** [comment]
Thank you for your answer, very good project, always looking forward to the update of the project!
