### ISSUE TITLE
does the c++ version support convert frame data to libtorch tensor?

### ISSUE THREAD

**Issue by Shengxiaolin** [Fonbet/argus-tensor-stream#8]
i think it will work but do not test, looking for some advice.

**Comment by BykadorovR** [comment]
Hi @Shengxiaolin,
Sorry for late responce, but somehow after github update all notifications about new issues just disappeared so I even haven't noticed yours. If you still need support, please specify what exactly you mean by "frame data"?

**Comment by BykadorovR** [comment]
If you want just convert uint8_t* data to at::Tensor you can use:
`torch::from_blob(frame, { height, width, 3 }, 
 c10::TensorOptions(at::kByte).device(torch::Device(at::kCUDA, 0));`
(just check as frame data is converted to at::Tensor for Python and [do the same](https://github.com/osai-ai/tensor-stream/blob/0827723d5ad3f970325d8446cf451894891cac08/src/Wrappers/WrapperPython.cpp#L313), there are almost no differences in approach)

**Comment by Shengxiaolin** [comment]
i didn‘t read the code carefully when i open this issue,and thanks for your detailed answers.
