### ISSUE TITLE
why tensor-stream can't use gpu 1 even i have set cuda_device to 1

### ISSUE THREAD

**Issue by muvanpersie** [Fonbet/argus-tensor-stream#9]
Hi, it is so helpful and appreciate with your brilliant work. But these days I find it will only use gpu 0 even i have set cuda_device to 1 with 2*1080ti on my computer. Can you help me with this problem? Thanks so much!

**Comment by BykadorovR** [comment]
Hi @muvanpersie,
Sorry for late responce.
Can you please provide the execution line, so I can test it on my side?

**Comment by BykadorovR** [comment]
Just double checked correctness cuda_device option via sample:
`python simple.py -i rtmp://37.228.119.44:1935/vod/big_buck_bunny.mp4 -fc RGB24 -w 720 -h 480 -o dump -n 100 --planes MERGED --cuda_device 0`
changed --cuda_device to 1 and 2 on machine with 3 GPU, observed that only choosen GPU was occupied. So need reproducer from you to understand the issue.
BTW, don't you restrict your GPU visibility somehow so tensor-stream just can't pick specified GPU?

**Comment by muvanpersie** [comment]
Hi, @BykadorovR , thanks for your reply.  The code of mine is like this, 
```
reader = TensorStreamConverter(path, cuda_device=gpu_id)
reader.initialize()
reader.start()
```
I have set gpu_id to 1,  and the following pics are the gpus usages before and after I run the code 
![before](https://user-images.githubusercontent.com/12514872/85352873-89547b80-b539-11ea-8d2a-ae058858a6bd.png)
![after](https://user-images.githubusercontent.com/12514872/85353463-de44c180-b53a-11ea-9596-410b2cf382fd.png)
It seems that the decode part was executed on gpu 1, but I dont know why the memory of gpu  0 was also consumed.

**Comment by muvanpersie** [comment]
So sorry to bother you, I think I have found the reason. It is the pytorch model initialized on gpu 0. Thanks for your  brilliant work and reply again so much.
